site_name: Easy Controls - ISSAC 
repo_url: https://github.com/danielwilczak101/EasyControls


theme:
  name: material
  features:
    - content.code.copy #Copy Code Block Icon
  
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Software:
    - Raspberry Pi: software/software.md
    - Arduino: software/arduino.md
  - Mechanical: mechanical/mechanical.md
  - Electrical: electrical/electrical.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # Icons
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


  # Content Tabs
  - pymdownx.tabbed:
      alternate_style: true 

# Plugins
plugins:
  - glightbox #Plugin to allow for zoom on images 
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
 
