M48
; DRILL file {KiCad 7.0.2-0} date 2023 May 05, Friday 21:51:05
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-05T21:51:05-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
%
G90
G05
T1
X4.0354Y-2.9331
X4.0354Y-5.2165
X6.0039Y-2.9331
X6.0039Y-5.2165
T0
M30
