M48
; DRILL file {KiCad (6.0.2)} date Fri Apr 29 01:07:22 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-04-29T01:07:22-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X3.56Y-2.53
X3.56Y-3.51
X4.84Y-2.53
X4.84Y-3.51
T0
M30
