M48
; DRILL file {KiCad (6.0.4)} date Sun Oct  2 20:23:56 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-02T20:23:56-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X5.5748Y-2.5197
X5.5748Y-4.4016
X7.2126Y-2.5276
X7.2126Y-4.4016
T0
M30
