M48
; DRILL file {KiCad 7.0.2-0} date 2024 February 16, Friday 15:53:19
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-16T15:53:19-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X102.5Y-74.5
X102.5Y-132.5
X152.5Y-74.5
X152.5Y-132.5
T0
M30
